### ISSUE TITLE
Add modern holiday Yom HaAliyah

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#132]
Yom HaAliyah (Aliyah Day) (Hebrew: יום העליה‎‎) is an Israeli national holiday celebrated annually on the tenth of the Hebrew month of Nisan. According to Wikipedia, this holiday will be observed first in 5777 (although it has been observed in a grassroots fashion for the past 4 years).

**Comment by alanadrubin** [comment]
Kol HaKavod! Yom HaAliyah honors Aliyah as a core value of the Jewish People & the State of Israel, including the ongoing positive contributions made by Olim throughout history. The 10th of Nisan was chosen for the date of this new holiday as the Torah says this is the anniversary of the first mass Aliyah when God told Joshua to lead all of Am Yisrael across the Jordan River into Eretz Yisrael at Gilgal. According to the new Knesset law, Israeli schools are also mandated to teach about the importance and beauty of Aliyah, a concept that connects every Jew in Israel, around Parshat Lech Lecha. Aliyah is an ideal that Jews have prayed for each day over thousands of years. Connecting the Biblical commandment to come Home in a contemporary vibrant context, and celebrate entering the Land of Israel amongst all of the Jewish People on the 10th of Nisan, is exactly what this modern Yom HaAliyah national holiday enshrines.

**Comment by yisraeldov** [comment]
Is there currently an option to only show traditional holidays?

**Comment by dsadinoff** [comment]
I'm so confused.  How does 10 Nisan fit in with 7 Marcheshvan here?
https://he.wikisource.org/wiki/%D7%97%D7%95%D7%A7_%D7%99%D7%95%D7%9D_%D7%94%D7%A2%D7%9C%D7%99%D7%99%D7%94

I bet someone figured out that while 10 Nisan makes historical sense, nobody would pay attention to it because it's during school vacation :)

**Comment by alanadrubin** [comment]
Yom HaAliyah is Israel's newest national holiday, and I understand why some make the mistake by placing it on the wrong date as its a bit complicated. Yom HaAliyah as the first clause of the Knesset law dictates, will always be marked on the 10th of the Hebrew month of Nisan, as that is what the holiday celebrates.
To copy/paste the Yom HaAliyah bill's first clause, of course its in Hebrew:

מטרתו של חוק זה לקבוע יום ציון שנתי להכרה בחשיבותה של העלייה לארץ ישראל כבסיס לקיומה של מדינת ישראל, להתפתחותה ולעיצובה כחברה רב תרבותית, ולציון מועד הכניסה לארץ ישראל שאירע ביום י' בניסן

Cheshvan is only when things like the Israeli school system or a cabinet meeting etc...  is mandated to discuss the idea of Aliyah, or Jewish immigration to the State of Israel. The Yom HaAliyah law created these supplementary other times to discuss Aliyah because on the 10th of Nisan, schools and some government bodies are on holiday. 

The official legal nationally celebrated Israeli holiday set up by the new law is the 10th of Nisan and rightfully so. Yom HaAliyah, like Yom HaAtzmaut, is a celebratory day. A day when kids should be out of school to celebrate with their families, and Knesset members should be around the country celebrating with their communities. Yom HaAliyah is a day to be honored amongst the People of Israel, and not just technically on paper, or with a small l'chaim in a Knesset hearing.

By the way, there are a few holidays in Israel that have secondary dates mandated for supplementary parts of the celebration....its a bit complicated, but nothing new for Israel, or the Jewish People for that matter.

Even a few news sources got it initially wrong because it is a bit complex. See the references below. The holiday bill that was created in the Knesset is clear that the official date of this new Israeli holiday and the reason for Yom HaAliyah is the 10th of Nisan celebration.

Some examples from major news sources on Yom HaAliyah as the 10th of Nisan, here:

2016: Times of Israel
http://jewishnews.timesofisrael.com/israel-approves-new-holiday-to-celebrate-new-immigrants/

2016: YNET
http://www.ynetnews.com/articles/0,7340,L-4817589,00.html

2016: Haaretz
http://www.haaretz.com/weekend/anglo-file/1.726833?v=25889A989187F43C1E25FBBF142DC48C

2016: ILTV
https://www.youtube.com/shared?ci=nSbU49d_gMc

2016: Israel HaYom
http://www.israelhayom.com/site/newsletter_article.php?id=34515

http://www.israelnationalnews.com/News/News.aspx/178843

2016: Algemeiner
http://www.algemeiner.com/2016/07/01/yom-haaliyah-they-actually-made-a-day-for-us/

2016: Breitbart
http://www.breitbart.com/jerusalem/2016/06/22/knesset-passes-new-yom-haaliyah-bill-national-holiday-celebrating-immigration/

2016: JNS
http://www.jns.org/latest-articles/2016/6/29/yom-haaliyah-they-made-a-day-for-us#.V78OPGbXenM

2016: JWIRE
http://www.jwire.com.au/new-national-holiday-israel/

http://www.tabletmag.com/scroll/166719/israels-knesset-proposes-national-aliyah-day

http://www.jta.org/2014/03/24/news-opinion/israel-middle-east/knesset-bill-would-create-aliyah-day

French:
http://www1.alliancefr.com/tag/yom-haaliyah

Spanish:
https://www.enlacejudio.com/2016/06/23/la-fiesta-nueva-israel-yom-haalia-10-nisan/


MK Micki Zohar in Knesset on the passing of Yom HaAliyah into law: 
https://youtu.be/xpgUPk2DnkI

**Comment by dsadinoff** [comment]
On Wed, Oct 5, 2016 at 4:16 PM, alanadrubin <notifications@github.com>
wrote:

> Yom HaAliyah is Israel's newest national holiday, and I understand why
> some make the mistake by placing it on the wrong date as its a bit
> complicated. Yom HaAliyah as the first clause of the Knesset law dictates,
> will always be marked on the 10th of the Hebrew month of Nisan, as that is
> what the holiday celebrates.
> To copy/paste the Yom HaAliyah bill's first clause, of course its in
> Hebrew:
>
> מטרתו של חוק זה לקבוע יום ציון שנתי להכרה בחשיבותה של העלייה לארץ ישראל
> כבסיס לקיומה של מדינת ישראל, להתפתחותה ולעיצובה כחברה רב תרבותית, ולציון
> ​​
> ​​
> מועד הכניסה לארץ ישראל שאירע ביום י' בניסן
>
>
​I don't think that sentence is complex.  It just suggests that we
celebrate an event which took place in the past on 10 Nisan...

יום העלייה יצוין מדי שנה ביום ז' בחשוון (להלן – יום העלייה).
... on 7 Cheshvan.

​
​I'm happy to entertain 7 Cheshvan as יום העלייה.
I'm happy to add
​
מועד הכניסה לארץ ישראל  for 10 Nisan (as an option).

It sounds like what you guys are asking for is that 10 Nisan is יום העלייה,
and 7 Cheshvan is יום העלייה (observed) a la Lincoln's birthday.  I don't
see it in this text, and I'm not inclined to do it until I see actual
evidence other than various news sources misquoting the law.


———
Danny Sadinoff
danny@sadinoff.com

**Comment by alanadrubin** [comment]
Hey Danny, I hear your take on it, so it for sure is worth watching then the author of the bill, MK Miki Zohar's speech on the floor of the Knesset upon the final passing of the Yom HaAliyah law, showing "Framers Intent" as it were: https://youtu.be/xpgUPk2DnkI

The text of the bill goes so far as to give a limited running list of all the places that Yom HaAliyah needs to be supplementarily "observed" in Cheshvan as opposed to the real holiday that is to be marked generally and nationally on the 10th of Nisan, hence a specific list of observances for the 10th of Nisan were not required in the text of the bill.

**Comment by dsadinoff** [comment]
Sorry, I remain unconvinced.  Speeches notwithstanding, it doesn't look
like they passed the law you're describing.​

I have no doubt that you're accurately describing what Zohar wanted, but it
seems there was back-and-forth on the subject
https://goo.gl/k0Qriz

...and the Nissan faction lost.


I'm not trying to be obstructionist, I just want to represent accurately
any official holidays.  ​

-Danny


———
Danny Sadinoff
danny@sadinoff.com

**Comment by alanadrubin** [comment]
Ha, the Nisan faction didn't loose and you aren't being obstructionist....it was actually the painfully difficult Sofa Landver who was the obstructionist. It was a Likud & Labor (Opposition & Coalition) bill that they worked on for about three years in the Knesset, and was always to be the 10th of Nisan. Because of Sofa Landver's need to have some of the kavod, she fought to have other commemorances for when she thought she would get more press coverage, hence the supplements of Cheshvan limited extra observances in schools etc... Cheshvan was the "gimme" to the cry baby Sofa by Likud & Labor, it wasn't a substantive change in the point of the Yom HaAliyah holiday national celebration.

The bill was primarily put together by MK Miki Zohar of Likud and MK Hilik Bar of Labor. Here is Hilik Bar's speech on the floor of the Knesset at the passing of the new holiday law: https://www.youtube.com/watch?v=y-X299Zndp0&feature=share

There would be no reason to give a specific limited list of where to celebrate a national holiday, unless that list was just the mandated extra "observances".  Hence the real national holiday is the 10th of Nisan, with limited supplementary observances in Cheshvan. But this is your website, so you do your thing. No need to argue amongst Jews...its all good regardless. The Jewish People should be so blessed to have such disagreements as to when amazing things are celebrated with simcha.

Maybe add the 10th of Nisan to HebCal as "Yom HaAliyah (marked)" which is pretty much how the text of the law reads.

Shana Tova!

**Comment by Scimonster** [comment]
Perhaps it's best to see how things play out. Cheshvan is soon, we'll see
what happens then.   The holiday list can be updated retroactively if
needed.

**Comment by alanadrubin** [comment]
Ha...Sababa.
But I can also tell you now what is going to happen in Cheshvan.
Sofa Landver will do a meaningless PR photo opp event at the Jerusalem Convention Center. Teachers in schools will spend an hour talking about the history of Aliyah and asking kids where their Saftas were born. 
The national communal celebrations for Yom HaAliyah will be in the evening of the 10th of Nisan when they have been and should be, with a mega pilgrimage in the day time down to the traditional site of Gilgal where Joshua crossed over the Jordan.

**Comment by dsadinoff** [comment]
Microsoft and Google have both added Yom HaAliyah = 7 Marcheshvan to their Israel calendars.

**Comment by mjradwin** [comment]
I'm marking this as closed, will be included in hebcal 4.10 release.
