### ISSUE TITLE
Inaccurate Shabbat times

### ISSUE THREAD

**Issue by nomadicmarc** [hebcal/hebcal#136]
I am in Udaipur, Rajasthan, India and you have listed candle lighting at 6:08pm meaning Shkia / sunset would be 6:36, while sunset is actually at 6:57. This could cause someone to break Shabbos before it is over so I felt it important to report immediately.
Thank you for everything and Shabbat SHALOM.

**Comment by mjradwin** [comment]
It looks like Hebcal is generating all candle-lighting times for India 30 minutes earlier than it should be. I checked Chenai, Mumbai, New Delhi and Bengaluru, and all were 30 minutes early. A hypothesis is that this may be due to a bug in our handling of the `Asia/Kolkata` timezone, which is defined as `GMT +5:30`. The half-hour might be handled incorrectly? Some investigation is needed.

**Comment by mjradwin** [comment]
Changes released in Hebcal 4.13
