### ISSUE TITLE
Feature request - distinguish between days to mention and real holidays

### ISSUE THREAD

**Issue by DimaK-tracxpoint** [hebcal/hebcal#160]
Dear contributors, 

I'd like to get an option to output only Shabbats and other days when "L"T avot ha-melacha" kinds of work are to be avoided. Or at least to check whether arbitrary date belongs to this kind.

Thanks

**Comment by rob613** [comment]
DimaK are you looking for a list of days with candle lighting times (for
start of Shabbos or Yom Tov)?  Would you also expect to see end times for
such periods, which could be up to 3 days plus about an hour?  How much in
advance would you expect to run the software to get this output?

I have been looking for a similar feature so that on power recovery a
computer can auto boot and query if the present time is within such a
period, and also to periodically check similarly and instruct other devices
if they should be in a restricted mode or not.

The best I was able to do was modify the hebcal software to show a 2-day
period starting "yesterday" and from the output I can determine the present
status with simple post processing.  I have not yet found a more elegant
solution, but having posted this feature request I now get notified when
anyone else posts anything.  Overloading the command line arguments for
halachic day and today would seem to match the concept of showing the
approximately 25 hour period starting with just prior to the most recent
sunset and ending after the next sunset.

A candle lighting time indicates that the present halachic day has melocho
restrictions.  A candle lighting time with a lack of havdolla time would
indicate that the period of restriction will continue for another day.

If this would help you I would be happy to share the minor change I used.

Chaim

**Comment by mjradwin** [comment]
Released in hebcal 5.3.0
