### ISSUE TITLE
Add the starting times for Fasts

### ISSUE THREAD

**Issue by feinstein** [hebcal/hebcal#165]
Fasts should have the starting and ending times just as Candle Lighting is

**Comment by mjradwin** [comment]
Fast start and end times have been released on the hebcal.com website as of November 2020. 

Minor fasts begin at Alot HaShachar (sun is 16.1° below the horizon in the morning) and end when 3 medium-sized stars are observable in the night sky (sun is 7.083° below the horizon in the evening).

We don't plan to backport this feature to C. The website is now implemented in Node.js, which uses https://github.com/hebcal/hebcal-es6 instead of this C implementation ( https://github.com/hebcal/hebcal )
