### ISSUE TITLE
Wrong candles time entrance

### ISSUE THREAD

**Issue by rt400** [hebcal/hebcal#175]
hi..
if i use this link :
 [https://www.hebcal.com/hebcal/?v=1&cfg=fc&start=2019-06-02&end=2019-06-08&maj=on&min=off&nx=off&mf=off%20&ss=off&mod=off&s=off&c=on&o=off&geo=pos&latitude=32.0667&longitude=34.7667&tzid=Asia/Jerusalem&m=42&lg=h](url)

the result : 
`[{"start":"2019-06-07T19:27:00","hebrew":"הדלקת נרות","className":"candles","allDay":false,"title":"הדלקת נרות"},
{"allDay":true,"title":"ערב שבועות","url":"https://www.hebcal.com/holidays/shavuot","description":"Festival of Weeks, commemorates the giving of the Torah at Mount Sinai","start":"2019-06-08","className":"holiday","hebrew":"ערב שבועות"},
{"className":"candles","hebrew":"הדלקת נרות","start":"2019-06-08T20:27:00","allDay":false,"title":"הדלקת נרות"}]`

i got that the holiday candles light is in 20:27 PM , this is mistake , looks that is a havdalah time.

thanks...

**Comment by mjradwin** [comment]
Is this a location in Israel or Diaspora? Be sure to specify &i=on if you
want Hebcal to think you are in Israel.

You get the &i=on behavior implicitly if you use &geo=geoname and you pick
a geonames location in Israel. But since you are specifying location by
lat/long then the default is &i=off. Shavuot is a 2-day holiday outside of
Israel.

For more details on how to use the API properly please read the
documentation:

https://www.hebcal.com/home/195/jewish-calendar-rest-api

--

**Comment by rt400** [comment]
still with i=on i got this :
`[{"allDay":false,"start":"2019-06-07T19:27:00","title":"הדלקת נרות","hebrew":"הדלקת נרות","className":"candles"},{"title":"ערב שבועות","hebrew":"ערב שבועות","allDay":true,"start":"2019-06-08","url":"https://www.hebcal.com/holidays/shavuot","className":"holiday","description":"Festival of Weeks, commemorates the giving of the Torah at Mount Sinai"},{"allDay":false,"start":"2019-06-08T20:27:00","title":"הדלקת נרות","hebrew":"הדלקת נרות","className":"candles"}]`

this year shavuot in israel is in Motzaei Shabbat so there is no candles light...

**Comment by rt400** [comment]
i also change the geo to geo by id 
[https://www.hebcal.com/hebcal/?v=1&cfg=fc&start=2019-06-02&end=2019-06-08&maj=on&min=off&nx=off&mf=off%20&ss=off&mod=off&s=off&c=on&o=off&i=on&&geo=geoname&geonameid=281184&m=42&lg=h](url)

and the result are the same :
`[{"title":"הדלקת נרות","hebrew":"הדלקת נרות","className":"candles","allDay":false,"start":"2019-06-07T19:02:00"},{"title":"ערב שבועות","hebrew":"ערב שבועות","description":"Festival of Weeks, commemorates the giving of the Torah at Mount Sinai","className":"holiday","url":"https://www.hebcal.com/holidays/shavuot","allDay":true,"start":"2019-06-08"},{"allDay":false,"start":"2019-06-08T20:25:00","className":"candles","title":"הדלקת נרות","hebrew":"הדלקת נרות"}]`

still the candles are 1 hour different...
there is a way to fix it ?

**Comment by mjradwin** [comment]
This isn't actually a bug. Hebcal is behaving correctly by giving a "havdalah" time as candle-lighting time.

Since Shavuot starts on Motzaei Shabbat (in both Israel and Diaspora), you couldn't possibly light candles 18 minutes before sunset on Saturday - that would be violating Shabbat.

So therefore, you light candles for the chag just as Shabbat is going out - e.g. Havdalah time.
