### ISSUE TITLE
Json array that change every weeks

### ISSUE THREAD

**Issue by Michaelben92** [hebcal/hebcal#177]
Hi, I send a request for jerusalem candle hour lightin and I parse it to integrate it into my html but the problem is that every weeks,the JSON Object is changing, sometimes the items array contains 6 keys and sometimes 2 and I need to update every weeks my Jquery request.

example of request  https://www.hebcal.com/shabbat/?cfg=json&geonameid=281184&lg=fr

This is the sample code Jquery that I did for parasha Bamidbar :  
`$.getJSON("https://www.hebcal.com/shabbat/?cfg=json&geonameid=281184&m=0&lg=fr", function (data) {
  var city = data.location.city;
  var candles = data.items[0]['title'].substring(22, 27);
  var date = data.items[1]['date'];
  var parasha = data.items[1]['title'].substring(9, 30);
  console.log(data);
  console.log(candles);
  console.log(parasha);
`

We can see that the value are not in the same place...
Is there any way to get every time the same Json object ? 
Thanks

**Comment by mjradwin** [comment]
Because the Shabbat API also returns different kinds of events, you need to iterate across the entire `data.items` array and look at each individual event to see if `data.items[i]['category'] === 'candles'`. 

And even when you have a candle-lighting event, please note that it could be for Shabbat (in which case it would be Friday night, so `new Date(data.items[i]['date']).getDay() === 5` or it could be candle-lighting for a holiday.

**Comment by Michaelben92** [comment]
Hi,
Thank you for your answer, I just don't understand the second part, how am I supposed to use the `new Date(data.items[i]['date']).getDay() === 5` ? is this a condition in order to know if the hour in 'category' is for Shabbat or an event ? 
Thanks

**Comment by mjradwin** [comment]
Yes, that is a condition you could use inside of an if statement to find
out if the current item occurs on a Friday.

To understand more, please read the JavaScript documentation for the Date
object and for the getDay() method.

Good luck!
