### ISSUE TITLE
Python wrapper for hebcal

### ISSUE THREAD

**Issue by EliezerIsrael** [hebcal/hebcal#178]
I'm interested in using the hebcal code in Python.  Has anyone worked to create a python wrapper for this, using cython, or otherwise?

**Comment by shimonzak** [comment]
i use python with restful api

**Comment by mjradwin** [comment]
@EliezerIsrael I know you originally posted this issue 3+ years ago. In the past year, I have made ports of Hebcal to JavaScript, Swift and Golang. 

Would it still be useful to Sefaria to have a native Python implementation of Hebcal, or did you find a good workaround in the interim? I think that might be easier to do a straight Python rewrite than to wrap the C code with cython.

**Comment by mjradwin** [comment]
We're going to close this as WONTFIX because it's too difficult to get the existing C code working cleanly in a way that's maintainable as a Python wrapper.

For now, we'd recommend you use [hdate via PyPI](https://pypi.org/project/hdate/) and if there are additional features to port from Hebcal, please ask, and we'll look into porting those as native Python implementations.
