### ISSUE TITLE
Inconsistent naming of Adar in API vs Docs

### ISSUE THREAD

**Issue by tremendus** [hebcal/hebcal#182]
The API docs state in the list of month names to use Adar1 and Adar2 - no spaces. 
https://www.hebcal.com/home/219/hebrew-date-converter-rest-api

"hm=Kislev – Hebrew month (Nisan, Iyyar, Sivan, Tamuz, Av, Elul, Tishrei, Cheshvan, Kislev, Tevet, Shvat, Adar1, Adar2)"

But JSON returned has a space - Adar 1 and Adar 2
https://www.hebcal.com/converter/?cfg=json&gy=2019&gm=2&gd=27&g2h=1
... "hm":"Adar I" ...

 - for those of us that use this as a lookup this is problematic.

UPDATE: in fact, sometimes Adar comes as simply 'Adar' with no number 1 or 2:
https://www.hebcal.com/converter/?cfg=json&gy=2020&gm=3&gd=1&g2h=1

UPDATE2: it also seems that Shevat is inconsistent. The docs state "Shvat" but the API returns "Sh'vat". 

Shalom

**Comment by mjradwin** [comment]
Thanks for this message. We have added a note to the API documentation clarifying how **Adar** is interpreted:

> In leap years, specifying **Adar** is the same as specifying **Adar2**. In non-leap years, all three of **Adar**, **Adar1**, and **Adar2** are considered equivalent.

The API is somewhat lenient in what it accepts. You can specify `sh%27vat` or `Sh%27vat` or `Shvat`. It will always consistently generate `Sh'vat` in the response.

Similarly, the API accepts all of `Adar1`, `Adar 1`, `Adar I`, `Adar2`, `Adar 2`, `Adar II`. Because the capital-i and the lowercase-L look the same in some fonts, we recommend using the numerals `1` and `2` in the API usage. In the generated responses, Hebcal always uses `Adar I` and `Adar II` for consistency and compatibility as we've done for over 20 years.
