### ISSUE TITLE
Array index shifting

### ISSUE THREAD

**Issue by mattpolanieckidev** [hebcal/hebcal#199]
Due to holidays the array index shifts randomly. How can I consistently pull just the candlelighting time at items[0] if the special holidays will bump it? 

https://mattpolanieckidev.github.io/shabbostime/

**Comment by mjradwin** [comment]
Your issue didn't mention it, but we infer from context that you're using the Shabbat Times API

https://www.hebcal.com/home/197/shabbat-times-rest-api

If this is the case, and you're specifically looking for Friday night or Erev Chag candle-lighting, you'll want to change your code to loop through `result.items` and test for `item.category === 'candles'` instead of assuming that `items[0]` is the Friday night candle-lighting event. If you specifically want to look for only Shabbat (e.g. Friday night) candle lighting, you'll also have to look at `item.date` and see if the day-of-week is Friday.

**Comment by mattpolanieckidev** [comment]
Thank you so much for the quick response. Could you please help point me in the right direction? Can this be accomplished by filtering on the array?

**Comment by mjradwin** [comment]
Yes, by filtering or searching. For example, if it were JavaScript, you could do something like this:

```js
const candleLighting = result.items.find((i) => i.category === 'candles');
```
