### ISSUE TITLE
How can I know if a certain Shabbat is Shabbat Mevarchim

### ISSUE THREAD

**Issue by UrielZohar** [hebcal/hebcal#225]
I read this issue - https://github.com/hebcal/hebcal/issues/207
which tells how to find Shabbat Mevarchim among a range of dates.

I need an API which I give a certain date of Shabbat and get in its "items" an item that tells that this Shabbat is also Shabbat Mevarchim.

For example - 5 Jun 2021 is Shabbat Mevarchim of Sivan , I tried the follow API but it gave me only the Shabbat times and didn't mentioned that this Shabbat is also a Shbbat Mevarchim - 
https://www.hebcal.com/shabbat?v=1&cfg=json&geonameid=293397&gy=2021&gm=6&gd=5&nx=on&nh=on&ss=on

How could I make it to tell also the this Shabbat is also Shabbat Mevarchim ?

**Comment by mjradwin** [comment]
Hi, thanks for using the Hebcal APIs.

Instead of using the Shabbat API, we'd recommend using the full Hebrew Calendar API. You can specify the date range using `start=YYYY-MM-DD` and `end=YYYY-MM-DD` Gregorian dates as follows:

https://www.hebcal.com/hebcal?v=1&cfg=json&geonameid=293397&start=2021-06-05&end=2021-06-05&nx=on&nh=on&ss=on

https://www.hebcal.com/hebcal?v=1&cfg=json&geonameid=293397&start=2021-06-12&end=2021-06-12&nx=on&nh=on&ss=on

Then, if the `items` array contains an event where the `category` is `mevarchim`, you'll know that the `date` of the item corresponds to a date of Shabbat Mevarchim
