### ISSUE TITLE
Missing objects in Jewish calendar REST API response

### ISSUE THREAD

**Issue by KheironG** [hebcal/hebcal#258]
I'm having two issues while integrating the Jewish calendar REST API into a React Native application.

Candle lighting times missing from response, when providing location based on gps coordinates and tzid.

Havdalah object missing from response, when the event occurs after midnight on the Saturday/Sunday.

**Comment by mjradwin** [comment]
Sorry to hear you are having trouble. Please post the exact  URL you are using and the output you receive? This would be helpful context to understand what you are receiving.

If candle lighting or Havdalah times are missing on all days, you are likely missing some required URL parameter.

If candle lighting or Havdalah are missing on some days, it's likely that it's a consequence of how the holidays fall during the week (for example there is Havdalah event when a 2-day Chag ends on Friday night because Shabbat begins).

Or, if your location happens to be at an extreme northern or southern latitude, the algorithm often cannot determine sunset times.

**Comment by mjradwin** [comment]
Also, please note that if you're integrating into a React Native application, you can also directly use the Hebcal javascript APIs without needing to have any network connectivity at all.

https://github.com/hebcal/hebcal-es6/blob/main/README.md#HebrewCalendar

For example:

```js
const {HebrewCalendar, Location} = require('@hebcal/core');
const events = HebrewCalendar.calendar({
  year: 1993,
  location: new Location(32.1836, 34.87386, true, 'Asia/Jerusalem'), // Ra'anana
  il: true,
  candlelighting: true,
});
```
