### ISSUE TITLE
City problem after New York

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#30]
Submitted by ted on 2011-08-02 08:08:58

hebcal version 3.9.1:
hebcal doesn't recognize cities after "New York" in the for loop in set_default_city, even with
--with-default-city="Winston-Salem NC" and having put "Winston-Salem NC" in cities.h.
This is true no matter whether the new city is inserted after or before "New York."

**Comment by acli** [comment]
I have confirmed this problem in hebcal 4.6. This is happening because localize_to_city in start.c is converting all non-alphas to spaces in the city specified by --with-default-city, but “Winston-Salem NC” has a hyphen, so if this is how the city is entered into cities.h the comparison will never succeed.

**Comment by mjradwin** [comment]
Closing this as Hebcal 5 has been rewritten in Golang
